export interface UserResponse {
    ID: string
    Code: string
    SessionID: string
    UserName: string
    FirstName: string
    LastName: string
    FirstNameEN: string
    LastNameEN: string
    PositionID: string
    AgentID: string
    DepartmentID: string
    Status: string
    AddLevel: string
    PhoneExtension: string
    Email: string
    Pin: string
    NickName: string
    ManagerID: string
    StartWorkDate: string
    EmployeeCode: string
    Mobile: string
    Remark: string
    RemarkActive: string
    RemarkInActive: string
    PositionLevelID: string
    NonPositionID: string
    UniqueCode: string
    LineID: string
    LockLoginUntil: string
    Channel: string
    IDCard: string
    IsStatement: string
    IsNextYear: string
    IsActive: string
    Phone: string
    UserType: string
    Department: string
    IsVerifyByOTP: string
    PositionName: string
    UnitID: string
    UnitExecutiveName: string
    GroupID: string
    GroupExecutiveName: string
    BranchID: string
    BranchName: string
    LevelCo: string
    AgentStatement: string
    IsForceDelete: string
}